language: elixir

addons:
  postgresql: '9.6'

env:
  global:
    - CI=true
    - PGDATABASE=packages_bot
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - PGHOST=localhost
    - DATABASE_URL=postgres://postgres:postgres@localhost/packages_bot
    - ARCHIVE_RENEW_INTERVAL_IN_SECONDS=3600
    - MELPA_BOT_TOKEN=fake_token
    - HEXPM_BOT_TOKEN=fake_token
    - RUBY_GEMS_BOT_TOKEN=fake_token
    - MIX_ENV=test

cache:
  directories:
    - "~/.hex"
    - "~/.mix"
    - deps

elixir:
  - '1.8'

otp_release:
  - '21.0'

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
  - mix coveralls.travis --pro

services:
  - postgresql

deploy:
  provider: script
  script: sh deploy.sh
